name: release
run-name: release
on:
  pull_request:
    types:
      - closed

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}

      - name: Create Tag
        run: |
          VERSION_NUMBER=$(cat version.txt)
          git tag ${VERSION_NUMBER}
          git push origin ${VERSION_NUMBER}
