name: initialize
run-name: initialize
on:
  create:

jobs:
  initiallize-repository:
    if: github.ref == 'refs/heads/${{ github.event.repository.default_branch }}'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: initialize repository
        shell: bash
        id: initialize_repository
        run: |
          python ./.github/workflows/create_default_branch_protection_ruleset.py ${{ github.repository }} ${{ secrets.GITHUB_TOKEN }}
