name: release
run-name: release
on:
  pull_request:
    types:
      - closed

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}

      - name: Create Tag
        id: create_tag
        run: |
          VERSION_NUMBER=$(cat version.txt)
          git tag ${VERSION_NUMBER}
          git push origin ${VERSION_NUMBER}
          echo "VERSION_NUMBER=${VERSION_NUMBER}" >> "$GITHUB_OUTPUT"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.create_tag.outputs.VERSION_NUMBER }}
          release_name: Release ${{ steps.create_tag.outputs.VERSION_NUMBER }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
